research_task:
  description: >
    Conduct thorough research on the latest industry trends. 
    Ensure to gather the most relevant and up-to-date information, including emerging patterns and innovations, 
    considering the current year is 2024.
  expected_output: >
     A list of 10 bullet points summarizing the most relevant and actionable insights about industry trends.
  agent: trend_researcher

blog_task:
  description: >
    Review the research findings and take an interresting topic and craft a well-structured, engaging blog post. 
    The post should be informative, easy to understand, and include key industry insights from the research.
  expected_output: >
    A fully written blog post formatted in markdown, capturing the essence of the research and presenting it in an engaging and coherent manner.
  agent: blogger

seo_article_task:
  description: >
    Research and draft a high-quality, SEO-optimized article based on the blog.
    Start by identifying relevant keywords, trending topics, and search terms.
    Use the research to craft an engaging article that includes:
    - Primary and secondary keywords
    - A clear structure with headings and subheadings
    - A compelling meta description
  expected_output: >
    An SEO-optimized article in markdown format:
    - Includes a title, introduction, body, and conclusion.
    - Proper use of headings and subheadings.
    - Highlighted keywords and a meta description.
  agent: seo_writer

commercial_script_task:
  description: >
    Research the target brand, product, or service and generate unique and engaging script ideas for commercial spots. 
    Ensure the scripts:
    - Align with the brand's tone and message.
    - Appeal to the target audience.
    - Include creative and memorable concepts.
  expected_output: >
    A markdown document containing:
    - A brief introduction of the brand, product, or service.
    - 3 to 5 script ideas with titles and short descriptions.
    - Key elements of each script, including storyline, key messages, and a call to action.
  agent: commercial_script_writer

hashtag_suggestion_task:
  description: >
    Research and identify the best hashtags for {campaign}. 
    Provide:
    - A brief description of the campaign objectives and its focus.
    - A curated list of hashtags tailored to the campaign's goals and audience.
    - Ensure hashtags are relevant, trending, and likely to boost visibility and engagement.
  expected_output: >
    A markdown document containing:
    - Campaign Description: A concise summary of the campaign's objectives and target focus.
    - Suggested Hashtags: A list of 10 to 15 hashtags, categorized as:
      - Trending hashtags
      - Campaign-specific hashtags
      - General high-engagement hashtags
  agent: hashtag_specialist

product_description_task:
  description: >
    Write engaging and SEO-optimized product descriptions for an e-commerce website. 
    Ensure that each description includes:
    - Key features and specifications.
    - Benefits and unique selling points.
    - A tone consistent with the brand's voice.
  expected_output: >
    A markdown document for the product {product_features} 
    - Product Name
    - Key Features (Bullet points)
    - Benefits and Description (Detailed paragraph)
    - Unique Selling Points (Short summary)
  agent: ecommerce_product_writer

short_form_script_task:
  description: >
    Write creative and engaging scripts for TikTok/YouTube Shorts based on the given theme: {tiktok/shorts theme}.
    Ensure the scripts:
    - Align with the platform's style and audience expectations.
    - Include a hook, engaging main content, and a clear call to action.
    - Are concise and fit within the time constraints of short-form video content.
  expected_output: >
    A markdown document containing:
    - Theme: {tiktok/shorts theme}.
    - Scripts: Provide 2 or 3 complete scripts for the short-form video, each with:
      - Hook: The opening line or action to grab attention.
      - Body: The main content or narrative.
      - Call to Action: How to engage the audience further (e.g., follow, like, comment).
  agent: short_form_scriptwriter

keyword_blog_topic_task:
  description: >
    Use the provided long-tail keywords to generate blog topics that are:
    - Relevant to the keywords.
    - Optimized for SEO.
    - Engaging and suitable for the target audience.
    Ensure the topics are specific and actionable, increasing their likelihood of ranking well and attracting readers.
  expected_output: >
    A markdown document containing:
    - List of Long-Tail Keywords: The provided keywords.
    - Blog Topics: A list of 5 to 10 blog topics based on the keywords, formatted as:
      - Keyword: [The long-tail keyword].
      - Topic: [The suggested blog topic].
  agent: keyword_blog_topic_creator

video_ad_idea_task:
  description: >
    Develop a set of creative ideas for video advertisements based on the given campaign objectives and target audience. 
    campaign:{campaign}
    Ensure the ideas:
    - Are tailored to the intended platform (e.g., TikTok, YouTube, Instagram).
    - Highlight key messaging in a visually compelling and emotionally engaging manner.
    - Include suggestions for tone, style, and narrative structure.
  expected_output: >
    A markdown document containing:
    - Campaign Objectives: A brief description of the campaign's goals and target audience.
    - Video Ad Ideas: A list of 5 to 7 advertisement concepts, each with:
      - Concept Title: A catchy name or title for the idea.
      - Concept Overview: A detailed explanation of the video's narrative and style.
      - Key Elements: Suggestions for visuals, tone, and messaging.
      - Target Platform: Recommended platform(s) for the concept.
  agent: video_ad_idea_creator

press_release_task:
  description: >
    Write a professional and engaging press release for the launch of a new product. 
    product details : {product_data}
    Ensure the press release:
    - Highlights the product's unique features and benefits.
    - Clearly communicates the launch details (e.g., date, availability, pricing).
    - Captures the brand voice and resonates with the target audience.
    - Follows a standard press release format with headline, subhead, body, and boilerplate.
  expected_output: >
    A markdown document containing:
    - Headline: A captivating title for the press release.
    - Subhead: A concise summary that complements the headline.
    - Body: A detailed description of the product launch, including key features, benefits, and quotes from stakeholders.
    - Boilerplate: A brief description of the company or brand.
    - Contact Information: Details for press inquiries.
  agent: press_release_writer





