research_task:
  description: >
    Conduct thorough research on the latest industry trends for {topic}. 
    Ensure to gather the most relevant and up-to-date information, including emerging patterns and innovations, 
    considering the current year is 2024.
  expected_output: >
     A list of 10 bullet points summarizing the most relevant and actionable insights about {topic}.
  agent: trend_researcher

blog_task:
  description: >
    Review the research findings and craft a well-structured, engaging blog post. 
    The post should be informative, easy to understand, and include key industry insights from the research.
  expected_output: >
    A fully written blog post formatted in markdown, capturing the essence of the research and presenting it in an engaging and coherent manner.
  agent: blogger
