research_task:
  description: >
    Conduct thorough research on the latest industry trends. 
    Ensure to gather the most relevant and up-to-date information, including emerging patterns and innovations, 
    considering the current year is 2024.
  expected_output: >
     A list of 10 bullet points summarizing the most relevant and actionable insights about industry trends.
  agent: trend_researcher

blog_task:
  description: >
    Review the research findings and take an interresting topic and craft a well-structured, engaging blog post. 
    The post should be informative, easy to understand, and include key industry insights from the research.
  expected_output: >
    A fully written blog post formatted in markdown, capturing the essence of the research and presenting it in an engaging and coherent manner.
  agent: blogger

seo_article_task:
  description: >
    Research and draft a high-quality, SEO-optimized article based on the blog.
    Start by identifying relevant keywords, trending topics, and search terms.
    Use the research to craft an engaging article that includes:
    - Primary and secondary keywords
    - A clear structure with headings and subheadings
    - A compelling meta description
  expected_output: >
    An SEO-optimized article in markdown format:
    - Includes a title, introduction, body, and conclusion.
    - Proper use of headings and subheadings.
    - Highlighted keywords and a meta description.
  agent: seo_writer

commercial_script_task:
  description: >
    Research the target brand, product, or service and generate unique and engaging script ideas for commercial spots. 
    Ensure the scripts:
    - Align with the brand's tone and message.
    - Appeal to the target audience.
    - Include creative and memorable concepts.
  expected_output: >
    A markdown document containing:
    - A brief introduction of the brand, product, or service.
    - 3 to 5 script ideas with titles and short descriptions.
    - Key elements of each script, including storyline, key messages, and a call to action.
  agent: commercial_script_writer

hashtag_suggestion_task:
  description: >
    Research and identify the best hashtags for {campaign}. 
    Provide:
    - A brief description of the campaign objectives and its focus.
    - A curated list of hashtags tailored to the campaign's goals and audience.
    - Ensure hashtags are relevant, trending, and likely to boost visibility and engagement.
  expected_output: >
    A markdown document containing:
    - Campaign Description: A concise summary of the campaign’s objectives and target focus.
    - Suggested Hashtags: A list of 10 to 15 hashtags, categorized as:
      - Trending hashtags
      - Campaign-specific hashtags
      - General high-engagement hashtags
  agent: hashtag_specialist

product_research_task:
  description: >
    Research and gather detailed information about all the products listed on the e-commerce website: {website_domain}.
    Collect data such as product features, specifications, benefits, pricing, and any unique selling points.
    Organize the data into a clear and structured format for further use.
  expected_output: >
    A structured list of products with detailed information, including:
    - Product Name
    - Key Features
    - Specifications
    - Benefits
    - Pricing
  agent: product_researcher

product_description_task:
  description: >
    Use the research data provided to create SEO-optimized and engaging product descriptions for each product.
    Ensure the descriptions include:
    - Product Name
    - Key Features and Specifications
    - Benefits and Unique Selling Points
    - A tone consistent with the e-commerce website's branding
  expected_output: >
    A markdown file with SEO-optimized product descriptions, formatted as:
    - Product Name: Title
    - Features: Bullet points
    - Description: Paragraph highlighting benefits and unique points
  agent: product_description_writer


